// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnluY9r-A75g_KBZwByXpslZUFYsaLvqg',
    appId: '1:115909101287:web:86939f0d7fc85ebe9e4442',
    messagingSenderId: '115909101287',
    projectId: 'spotify-app-1410',
    authDomain: 'spotify-app-1410.firebaseapp.com',
    storageBucket: 'spotify-app-1410.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg7FmDJQPU3eqP-Ix9gKeBtim_98GPqpA',
    appId: '1:115909101287:android:f1d9584431a46c669e4442',
    messagingSenderId: '115909101287',
    projectId: 'spotify-app-1410',
    storageBucket: 'spotify-app-1410.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWCoXc31Afdt1r7UKx6lyVfW5278bRGHo',
    appId: '1:115909101287:ios:8ec38c8286ec76049e4442',
    messagingSenderId: '115909101287',
    projectId: 'spotify-app-1410',
    storageBucket: 'spotify-app-1410.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWCoXc31Afdt1r7UKx6lyVfW5278bRGHo',
    appId: '1:115909101287:ios:8ec38c8286ec76049e4442',
    messagingSenderId: '115909101287',
    projectId: 'spotify-app-1410',
    storageBucket: 'spotify-app-1410.firebasestorage.app',
    iosBundleId: 'com.example.taxiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnluY9r-A75g_KBZwByXpslZUFYsaLvqg',
    appId: '1:115909101287:web:85cae100b1f5ebb69e4442',
    messagingSenderId: '115909101287',
    projectId: 'spotify-app-1410',
    authDomain: 'spotify-app-1410.firebaseapp.com',
    storageBucket: 'spotify-app-1410.firebasestorage.app',
  );
}
